language: go

go:
    - 1.13
    - tip

script:
    - go test -race -v -bench=. github.com/xjdrew/kone/geoip
    - go test -race -v -bench=. github.com/xjdrew/kone/tcpip
    - go test -race -v -bench=. github.com/xjdrew/kone/k1
